### ISSUE TITLE
Notifications not working

### ISSUE THREAD

**Issue by ebrahim-moshaya** [inokappa/chef-handler-jenkins_notifier#3]
After a while realising you need to create a "External Job" for allowing for /postBuildResult, I see no notifications being sent back to this job following a successful cookbook converge

**Comment by inokappa** [comment]
@ebrahim-moshaya 

Thank you for your issue.

>After a while realising you need to create a "External Job" for allowing for /postBuildResult,

I see.
This gem has been created as a notification purpose to the External Job.
I'll write to the document to make the External Job in first.

Thank you.

**Comment by inokappa** [comment]
closed.

Thank you.
